name: Bug Report
description: File a bug report
title: "[BUG]: "
labels: ["bug", "triage"]
assignees:
  - ZotyDev
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: platforms
    attributes:
      label: The platforms where this bug happens
      multiple: true
      options:
        - Windows
        - Emscripten
  - type: dropdown
    id: applications
    attributes:
      label: The applications where this bug happens
      multiple: true
      options:
        - Engine
        - Test
        - Client
        - Server
        - Editor
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log outputs. This will be automatically formatted into code, so no needfor backticks.
      render: Shell
