#include "uepch.h"
#include "Script/LuaExposer.h"

#include "Math/Easing/EasingLua.h"
#include "Core/LogLua.h"

#include "Input/keyCodes.h"
#include "Input/gamePadCodes.h"
#include "Input/mouseCodes.h"

namespace UE
{
	UEResult ExposeCoreToLua(LuneStack stack)
	{
		LuneModule Core("Core");
		Core
			.Add(LuneModule("Math")
				.Add(LuneModule("Easing")
					.Add("EaseInBack", lua_EaseInBack)
					.Add("EaseOutBack", lua_EaseOutBack)
					.Add("EaseInOutBack", lua_EaseInOutBack)
					.Add("EaseInBounce", lua_EaseInBounce)
					.Add("EaseOutBounce", lua_EaseOutBounce)
					.Add("EaseInOutBounce", lua_EaseInOutBounce)
					.Add("EaseInCirc", lua_EaseInCirc)
					.Add("EaseOutCirc", lua_EaseOutCirc)
					.Add("EaseInOutCirc", lua_EaseInOutCirc)
					.Add("EaseInCubic", lua_EaseInCubic)
					.Add("EaseOutCubic", lua_EaseOutCubic)
					.Add("EaseInOutCubic", lua_EaseInOutCubic)
					.Add("EaseInElastic", lua_EaseInElastic)
					.Add("EaseOutElastic", lua_EaseOutElastic)
					.Add("EaseInOutElastic", lua_EaseInOutElastic)
					.Add("EaseInExpo", lua_EaseInExpo)
					.Add("EaseOutExpo", lua_EaseOutExpo)
					.Add("EaseInOutExpo", lua_EaseInOutExpo)
					.Add("EaseInQuad", lua_EaseInQuad)
					.Add("EaseOutQuad", lua_EaseOutQuad)
					.Add("EaseInOutQuad", lua_EaseInOutQuad)
					.Add("EaseInQuart", lua_EaseInQuart)
					.Add("EaseOutQuart", lua_EaseOutQuart)
					.Add("EaseInOutQuart", lua_EaseInOutQuart)
					.Add("EaseInQuint", lua_EaseInQuint)
					.Add("EaseOutQuint", lua_EaseOutQuint)
					.Add("EaseInOutQuint", lua_EaseInOutQuint)
					.Add("EaseInSine", lua_EaseInSine)
					.Add("EaseOutSine", lua_EaseOutSine)
					.Add("EaseInOutSine", lua_EaseInOutSine)
				) // Easing
			) // Math
			.Add(LuneClass("Logger")
				.AddCtor("Create", lua_CreateLogger)
				.AddCtor("Get", lua_GetLogger)
				.Add("Trace", lua_LoggerTrace)
				.Add("Info", lua_LoggerInfo)
				.Add("Warn", lua_LoggerWarn)
				.Add("Error", lua_LoggerError)
				.Add("Critical", lua_LoggerCritical)
			) // Logger
			.Add(LuneModule("Events")
				.Add(LuneModule("Register")
				) // Register
			) // Events
			.Add(LuneModule("Input")
				.Add(LuneModule("Keyboard")
					.Add(LuneModule("Codes")
						.Add("Space",			(UEUint16)KeyCode::Space)
						.Add("Apostrophe",		(UEUint16)KeyCode::Apostrophe)
						.Add("Comma",			(UEUint16)KeyCode::Comma)
						.Add("Minus",			(UEUint16)KeyCode::Minus)
						.Add("Period",			(UEUint16)KeyCode::Period)
						.Add("Slash",			(UEUint16)KeyCode::Slash)
						.Add("D0",				(UEUint16)KeyCode::D0)
						.Add("D1",				(UEUint16)KeyCode::D1)
						.Add("D2",				(UEUint16)KeyCode::D2)
						.Add("D3",				(UEUint16)KeyCode::D3)
						.Add("D4",				(UEUint16)KeyCode::D4)
						.Add("D5",				(UEUint16)KeyCode::D5)
						.Add("D6",				(UEUint16)KeyCode::D6)
						.Add("D7",				(UEUint16)KeyCode::D7)
						.Add("D8",				(UEUint16)KeyCode::D8)
						.Add("D9",				(UEUint16)KeyCode::D9)
						.Add("Semicolon",		(UEUint16)KeyCode::Semicolon)
						.Add("Equal",			(UEUint16)KeyCode::Equal)
						.Add("A",				(UEUint16)KeyCode::A)
						.Add("B",				(UEUint16)KeyCode::B)
						.Add("C",				(UEUint16)KeyCode::C)
						.Add("D",				(UEUint16)KeyCode::D)
						.Add("E",				(UEUint16)KeyCode::E)
						.Add("F",				(UEUint16)KeyCode::F)
						.Add("G",				(UEUint16)KeyCode::G)
						.Add("H",				(UEUint16)KeyCode::H)
						.Add("I",				(UEUint16)KeyCode::I)
						.Add("J",				(UEUint16)KeyCode::J)
						.Add("K",				(UEUint16)KeyCode::K)
						.Add("L",				(UEUint16)KeyCode::L)
						.Add("M",				(UEUint16)KeyCode::M)
						.Add("N",				(UEUint16)KeyCode::N)
						.Add("O",				(UEUint16)KeyCode::O)
						.Add("P",				(UEUint16)KeyCode::P)
						.Add("Q",				(UEUint16)KeyCode::Q)
						.Add("R",				(UEUint16)KeyCode::R)
						.Add("S",				(UEUint16)KeyCode::S)
						.Add("T",				(UEUint16)KeyCode::T)
						.Add("U",				(UEUint16)KeyCode::U)
						.Add("V",				(UEUint16)KeyCode::V)
						.Add("W",				(UEUint16)KeyCode::W)
						.Add("X",				(UEUint16)KeyCode::X)
						.Add("Y",				(UEUint16)KeyCode::Y)
						.Add("Z",				(UEUint16)KeyCode::Z)
						.Add("LeftBracket",		(UEUint16)KeyCode::LeftBracket)
						.Add("Backslash",		(UEUint16)KeyCode::Backslash)
						.Add("RightBracket",	(UEUint16)KeyCode::RightBracket)
						.Add("GraveAccent",		(UEUint16)KeyCode::GraveAccent)
						.Add("World1",			(UEUint16)KeyCode::World1)
						.Add("World2",			(UEUint16)KeyCode::World2)
						.Add("Escape",			(UEUint16)KeyCode::Escape)
						.Add("Enter",			(UEUint16)KeyCode::Enter)
						.Add("Tab",				(UEUint16)KeyCode::Tab)
						.Add("Backspace",		(UEUint16)KeyCode::Backspace)
						.Add("Insert",			(UEUint16)KeyCode::Insert)
						.Add("Delete",			(UEUint16)KeyCode::Delete)
						.Add("Right",			(UEUint16)KeyCode::Right)
						.Add("Left",			(UEUint16)KeyCode::Left)
						.Add("Down",			(UEUint16)KeyCode::Down)
						.Add("Up",				(UEUint16)KeyCode::Up)
						.Add("PageUp",			(UEUint16)KeyCode::PageUp)
						.Add("PageDown",		(UEUint16)KeyCode::PageDown)
						.Add("Home",			(UEUint16)KeyCode::Home)
						.Add("End",				(UEUint16)KeyCode::End)
						.Add("CapsLock",		(UEUint16)KeyCode::CapsLock)
						.Add("ScrollLock",		(UEUint16)KeyCode::ScrollLock)
						.Add("NumLock",			(UEUint16)KeyCode::NumLock)
						.Add("PrintScreen",		(UEUint16)KeyCode::PrintScreen)
						.Add("Pause",			(UEUint16)KeyCode::Pause)
						.Add("F1",				(UEUint16)KeyCode::F1)
						.Add("F2",				(UEUint16)KeyCode::F2)
						.Add("F3",				(UEUint16)KeyCode::F3)
						.Add("F4",				(UEUint16)KeyCode::F4)
						.Add("F5",				(UEUint16)KeyCode::F5)
						.Add("F6",				(UEUint16)KeyCode::F6)
						.Add("F7",				(UEUint16)KeyCode::F7)
						.Add("F8",				(UEUint16)KeyCode::F8)
						.Add("F9",				(UEUint16)KeyCode::F9)
						.Add("F10",				(UEUint16)KeyCode::F10)
						.Add("F11",				(UEUint16)KeyCode::F11)
						.Add("F12",				(UEUint16)KeyCode::F12)
						.Add("F13",				(UEUint16)KeyCode::F13)
						.Add("F14",				(UEUint16)KeyCode::F14)
						.Add("F15",				(UEUint16)KeyCode::F15)
						.Add("F16",				(UEUint16)KeyCode::F16)
						.Add("F17",				(UEUint16)KeyCode::F17)
						.Add("F18",				(UEUint16)KeyCode::F18)
						.Add("F19",				(UEUint16)KeyCode::F19)
						.Add("F20",				(UEUint16)KeyCode::F20)
						.Add("F21",				(UEUint16)KeyCode::F21)
						.Add("F22",				(UEUint16)KeyCode::F22)
						.Add("F23",				(UEUint16)KeyCode::F23)
						.Add("F24",				(UEUint16)KeyCode::F24)
						.Add("F25",				(UEUint16)KeyCode::F25)
						.Add("KP0",				(UEUint16)KeyCode::KP0)
						.Add("KP1",				(UEUint16)KeyCode::KP1)
						.Add("KP2",				(UEUint16)KeyCode::KP2)
						.Add("KP3",				(UEUint16)KeyCode::KP3)
						.Add("KP4",				(UEUint16)KeyCode::KP4)
						.Add("KP5",				(UEUint16)KeyCode::KP5)
						.Add("KP6",				(UEUint16)KeyCode::KP6)
						.Add("KP7",				(UEUint16)KeyCode::KP7)
						.Add("KP8",				(UEUint16)KeyCode::KP8)
						.Add("KP9",				(UEUint16)KeyCode::KP9)
						.Add("KPDecimal",		(UEUint16)KeyCode::KPDecimal)
						.Add("KPDivide",		(UEUint16)KeyCode::KPDivide)
						.Add("KPMultiply",		(UEUint16)KeyCode::KPMultiply)
						.Add("KPSubstract",		(UEUint16)KeyCode::KPSubtract)
						.Add("KPAdd",			(UEUint16)KeyCode::KPAdd)
						.Add("KPEnter",			(UEUint16)KeyCode::KPEnter)
						.Add("KPEqual",			(UEUint16)KeyCode::KPEqual)
						.Add("LeftShift",		(UEUint16)KeyCode::LeftShift)
						.Add("LeftControl",		(UEUint16)KeyCode::LeftControl)
						.Add("LeftAlt",			(UEUint16)KeyCode::LeftAlt)
						.Add("LeftSuper",		(UEUint16)KeyCode::LeftSuper)
						.Add("RightShift",		(UEUint16)KeyCode::RightShift)
						.Add("RightControl",	(UEUint16)KeyCode::RightControl)
						.Add("RightAlt",		(UEUint16)KeyCode::RightAlt)
						.Add("RightSuper",		(UEUint16)KeyCode::RightSuper)
						.Add("Menu",			(UEUint16)KeyCode::Menu)
					) // Codes
				) // Keyboard

				.Add(LuneModule("Mouse")
					.Add(LuneModule("Codes")
						.Add("B0", (UEUint16)MouseCode::B0)
						.Add("B1", (UEUint16)MouseCode::B1)
						.Add("B2", (UEUint16)MouseCode::B2)
						.Add("B3", (UEUint16)MouseCode::B3)
						.Add("B4", (UEUint16)MouseCode::B4)
						.Add("B5", (UEUint16)MouseCode::B5)
						.Add("B6", (UEUint16)MouseCode::B6)
						.Add("B7", (UEUint16)MouseCode::B7)
						.Add("Left", (UEUint16)MouseCode::Left)
						.Add("Right", (UEUint16)MouseCode::Right)
						.Add("Middle", (UEUint16)MouseCode::Middle)
					) // Codes
				) // Mouse

				.Add(LuneModule("Gamepad")
					.Add(LuneModule("Codes")
						.Add("A",				(UEUint16)GamepadCode::A)
						.Add("B",				(UEUint16)GamepadCode::B)
						.Add("X",				(UEUint16)GamepadCode::X)
						.Add("Y",				(UEUint16)GamepadCode::Y)
						.Add("LeftBumper",		(UEUint16)GamepadCode::LeftBumper)
						.Add("RightBumper",		(UEUint16)GamepadCode::RightBumper)
						.Add("Back",			(UEUint16)GamepadCode::Back)
						.Add("Start",			(UEUint16)GamepadCode::Start)
						.Add("Guide",			(UEUint16)GamepadCode::Guide)
						.Add("LeftThumb",		(UEUint16)GamepadCode::LeftThumb)
						.Add("RightThumb",		(UEUint16)GamepadCode::RightThumb)
						.Add("DPadUp",			(UEUint16)GamepadCode::DPadUp)
						.Add("DPadRight",		(UEUint16)GamepadCode::DPadRight)
						.Add("DPadDown",		(UEUint16)GamepadCode::DPadDown)
						.Add("DPadLeft",		(UEUint16)GamepadCode::DPadLeft)
						.Add("Cross",			(UEUint16)GamepadCode::Cross)
						.Add("Circle",			(UEUint16)GamepadCode::Circle)
						.Add("Square",			(UEUint16)GamepadCode::Square)
						.Add("Triangle",		(UEUint16)GamepadCode::Triangle)
						.Add("LeftX",			(UEUint16)GamepadCode::LeftX)
						.Add("LeftY",			(UEUint16)GamepadCode::LeftY)
						.Add("RightX",			(UEUint16)GamepadCode::RightX)
						.Add("RightY",			(UEUint16)GamepadCode::RightY)
						.Add("LeftTrigger",		(UEUint16)GamepadCode::LeftTrigger)
						.Add("RightTrigger",	(UEUint16)GamepadCode::RightTrigger)
					) // Codes
				) // Gamepad

			); // Input
		
		Core.Register(stack);

		return UEResult::Success;
	}
}