name: Windows

on:
  push:
    branches: [ "refactor" ]
  pull_request:
  workflow_dispatch:

jobs:
  clang:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Install CLang
        run: curl -fsSL -o LLVM15.exe https://github.com/llvm/llvm-project/releases/download/llvmorg-15.0.0/LLVM-15.0.0-win64.exe ; 7z x LLVM15.exe -y -o"C:/Program Files/LLVM"
      - name: CMake Build
        run: Scripts/Windows/BuildDebug.cmd
      - name: Compile
        run: Scripts/Windows/Compile.cmd
